# Use the standard Microsoft VS Code Codespaces image as a starting point
FROM mcr.microsoft.com/devcontainers/typescript-node

# Install MongoDB
#RUN sudo apt-get update \
#    && sudo apt-get install -y mongodb \
#    && sudo mkdir -p /dbfiles


# Start MongoDB with the specified db location
#CMD ["mongod", "--dbpath", "/dbfiles"]
